// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    $('.notesite').hover(function() {
      $(this).animate({
        'font-size': '1200%'
      }, 200);
    }, function() {
      $(this).animate({
        'font-size': '1140%'
      }, 200);
    }).on('click', function(e) {
      if ($('div#resume').hasClass("open")) {
        return $('div#resume').removeClass("open", 400);
      } else {
        return $('div#resume').addClass("open", 400);
      }
    });
    return;
    $('#resume .hide').on('click', function(e) {
      $('#resume').animate({
        'height': '0'
      }, 300);
    });
  });

}).call(this);
