// Generated by CoffeeScript 1.6.3
(function() {
  var CVETable, InsTable, SWTable, Table, TableInterfaz,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TableInterfaz = (function() {
    function TableInterfaz(url, flavours) {
      alert(typeof url);
      if (typeof url === "string" && typeof flavours === "string") {
        $.getJSON(url, {}, function(data) {
          switch (data.node_type) {
            case 'CVEs':
              return new CVETable(data);
            case 'Software':
              return new SWTable(data);
            case 'Instances':
              return new InsTable(data, flavours);
          }
        });
      } else if (typeof url === "object") {
        switch (url.node_type) {
          case 'CVEs':
            new CVETable(url);
            break;
          case 'Software':
            new SWTable(url);
            break;
          case 'Instances':
            new InsTable(url, flavours);
        }
      }
    }

    return TableInterfaz;

  })();

  Table = (function() {
    function Table() {}

    Table.prototype.setPriority = function(cvss) {
      if (cvss > 4) {
        return 'red';
      } else if (cvss === 0) {
        return 'green';
      } else {
        return 'yellow';
      }
    };

    Table.prototype.parseDate = function(d) {
      var dd;
      dd = d.slice(0, 10).split('-');
      return dd[2] + "/" + dd[1] + "/" + dd[0];
    };

    return Table;

  })();

  InsTable = (function(_super) {
    __extends(InsTable, _super);

    function InsTable(data, flav) {
      var div;
      div = InsTable.paint(data, flav);
      $('#instances').append(div);
    }

    InsTable.paint = function(data, flav) {
      var toret;
      toret = '<table class="instances row"><thead><tr><th></th><th></th><th></th></tr></thead><tbody>';
      $.each(data.instances, function() {
        return toret += InsTable.addItem(this, flav);
      });
      return toret += '</tbody></table>';
    };

    InsTable.addItem = function(item, flav) {
      var art;
      art = "<tr><td>" + item.num + "</td><td>" + item.flavour + "</td>";
      $.each(flav.flavours, function() {
        if (this.name === item.flavour) {
          return art += "<td>" + this.memory + "</td><td>" + this.disk + "</td><td>" + this.vcpu + "</td></tr>";
        }
      });
      return art;
    };

    return InsTable;

  })(Table);

  CVETable = (function(_super) {
    __extends(CVETable, _super);

    function CVETable(data) {
      var div;
      div = "<h3>" + data.node_type + ": " + data.name + "</h3>";
      div += CVETable.paint(data);
      $('#breadcrumb').append('<li>CVE</li>');
      $('.table').empty().append(div);
      $('#cvetable article').click(function(event) {
        return $(this).toggleClass("viewfull", 400);
      });
      return;
    }

    CVETable.paint = function(data) {
      var toret;
      toret = '<div id="cvetable"><article id="leyend"><p class="risk"><span>Riesgo</span></p><p class="known"><span>Conocido desde </span></p><p class="updated"><span>Última actualizaci&oacute;n </span></p><p class="cod"><span>Código</span></p></article>';
      $.each(data.cve, function() {
        return toret += CVETable.addItem(this);
      });
      return toret += '</div>';
    };

    CVETable.addItem = function(item) {
      var art;
      art = "<article data-cvss='" + item.cvss;
      art += "' id='" + item.cve;
      art += "' class='cve";
      art += "'><p class='risk " + Table.prototype.setPriority(item.cvss) + "'>" + item.cvss;
      art += "</p><p class='known'>" + CVETable.prototype.parseDate(item.published);
      art += "</p><p class='updated'>" + CVETable.prototype.parseDate(item.modified);
      art += "</p><p class='cod'>" + item.cve;
      art += "</p><div class='cve-more'><span>Summary: </span>" + item.summary;
      art += "</div></article>";
      return art;
    };

    return CVETable;

  })(Table);

  SWTable = (function(_super) {
    __extends(SWTable, _super);

    function SWTable(data) {
      var div;
      div = "<h3>" + data.node_type + " de " + data.id;
      if (data["for"] === "Machine") {
        div += " (M&aacute;quina)</h3>";
      } else {
        div += "</h3>";
      }
      div += SWTable.paint(data);
      $('#breadcrumb').append('<li><a>Software</a></li>');
      $('.table').empty().append(div);
      $('button.details').click(function(event) {
        $(this).parent().toggleClass("viewfull", 400);
      });
      $('button.viewFullList').click(function(event) {
        TableInterfaz("assets/force.json");
      });
    }

    SWTable.paint = function(data) {
      var toret;
      toret = '<div id="swtable"><article id="leyend"><p class="cve_critical"><span>Critical</span></p><p class="cve_warning"><span>Warning</span></p><p class="sw_name"><span>Software</span></p><p class="version"><span>Versi&oacute;n</span></p></article>';
      $.each(data.sw, function() {
        return toret += SWTable.addItem(this);
      });
      return toret += '</div>';
    };

    SWTable.addItem = function(item) {
      var art;
      art = '<article id="' + item.publisher + '-' + item.software + '-' + item.version + '" class="software ' + item.publisher + '">';
      art += '<p class="cve_critical">' + item.cve_critical + '</p>';
      art += '<p class="cve_warning">' + item.cve_warning + '</p>';
      art += '<p class="sw_name">' + item.publisher + ' ' + item.software + '</p>';
      art += '<p class="version">' + item.version + '</p>';
      art += '<button class="details">Detalles</button><div>';
      $.each(item.cve, function() {
        return art += '<article><p><span class="risk ' + SWTable.prototype.setPriority(this.cvss) + '">' + this.cvss + '</span><p><span class="cve_id">' + this.cve + '</span></p><p><span class="known">' + CVETable.prototype.parseDate(this.published) + '</span></p></article>';
      });
      art += '</div>';
      art += '<button class="viewFullList">Ver m&aacute;s</button>';
      return art += '</article>';
    };

    return SWTable;

  })(Table);

  $(function() {
    var flavours, instances;
    instances = {
      "node_type": "Instances",
      "instances": [
        {
          "flavour": "tiny",
          "num": "3"
        }, {
          "flavour": "xlarge",
          "num": "8"
        }
      ]
    };
    flavours = {
      "node_type": "flavours",
      "flavours": [
        {
          "id": "1",
          "name": "tiny",
          "memory": "512MB",
          "disk": "0",
          "vcpu": "1"
        }, {
          "id": "5",
          "name": "xlarge",
          "memory": "2GB",
          "disk": "5TB",
          "vcpu": "12"
        }
      ]
    };
    return TableInterfaz(instances, flavours);
  });

}).call(this);
